### ISSUE TITLE
sparql endpoint appears to be down

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-ont#33]
Queries from the COR interface are not working. See screenshot.

<img width="1128" alt="screen shot 2017-01-28 at 8 09 43 pm" src="https://cloud.githubusercontent.com/assets/1266896/22401789/0286f0c2-e596-11e6-8820-32150d68df3d.png">

**Comment by carueda** [comment]
Perhaps a cache issue in your case? I just tried and it worked for me, including with a cache-clearing and hard refresh..

![2017-01-29_2113](https://cloud.githubusercontent.com/assets/556505/22412923/08e274be-e668-11e6-8e2b-660bfe64d142.png)

![2017-01-29_2114](https://cloud.githubusercontent.com/assets/556505/22412945/401cc452-e668-11e6-88d4-88d0e894263f.png)

**Comment by graybeal** [comment]
Works fine for me now too, without any cache clearing or anything. So, cool.
