### ISSUE TITLE
any additional mechanisms for format/serialization resolution?

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-ont#55]
The ORR supports two mechanisms to resolve ontology and term requests in a desired format or serialization:  i) **content negotiation** as the main mechanism for programmatic access; and ii) via `format` parameter as a convenience mainly for users when entering the request in a browser.

The resolution of desired format via 'file-type extension' in previous major version 2 has not been implemented in v3. This entry is to expand a bit on the rationale for having postponed a similar "feature" in v3, and to get reactions toward determining whether there's an actual need for such file-type extension mechanism.

- The `format` parameter makes very explicit the desired effect of the request. On the other hand, a request with file extension, although it might look explicit about the format, can actually be at least a bit confusing when there's actually an entry with such file extension as part of the original IRI, while at the same time the request is to resolve the contents in a serialization different from the original submission. For example, http://mmisw.org/ont/ANZRC/ANZRC_Codes.owl.n3. Contrast this with the use of the `format` parameter: eg., http://mmisw.org/ont/ANZRC/ANZRC_Codes.owl?format=n3.

- As a non-functional aspect, when processing an IRI request that includes some file extension, but that does not exist in the system, the backend would have to perform extra logic for possibly finding the requested IRI without that file extension. Perhaps not a very expensive operation but with an impact on performance anyway.

**Comment by dr-shorthair** [comment]
Suggest also supporting `_format` which is the key built-in to the Linked Data API
see https://github.com/UKGovLD/linked-data-api/blob/wiki/API_Query_Parameters.md

**Comment by carueda** [comment]
I have implemented this "file-type extension" resolution.
Also, included check for `_format` parameter in case `format` is not given.

All of this available as of v.3.6.7 of the system.

**Comment by carueda** [comment]
COR instance just upgraded to v3.6.7. 
See https://github.com/ESIPFed/sweet/issues/51

**Comment by carueda** [comment]
The recognized formats via file extension (or `format` or `_format` parameter) are:

| File&nbsp;ext  | Mime type             | Reference|
|-----------|------------------------|----------|
| `rdf`     | application/rdf+xml    | https://www.w3.org/TR/REC-rdf-syntax/ |
| `owl`     | application/rdf+xml    | https://www.w3.org/TR/REC-rdf-syntax/ |
| `owx`     | application/owl+xml    | https://www.w3.org/TR/owl-xml-serialization/ |
| `jsonld`  | application/json+ld    | http://www.ietf.org/rfc/rfc6839.txt |
| `n3`      | text/n3                | http://www.w3.org/TeamSubmission/n3/ |
| `ttl`     | text/turtle            | http://www.w3.org/TeamSubmission/turtle/ |
| `nt`      | text/plain             | http://www.w3.org/TR/2004/REC-rdf-testcases-20040210/ |
| `nq`      | application/n-quads    | http://www.w3.org/TR/2013/NOTE-n-quads-20130409/ |
| `trig`    | application/trig       | http://www.w3.org/TR/2013/WD-trig-20130409/ |
| `rj`      | application/rdf+json   | https://dvcs.w3.org/hg/rdf/raw-file/default/rdf-json/index.html |
