### ISSUE TITLE
remove requirement for format parameter

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-ont#63]
Currently, even for the special value `_guess`, such `format` parameter is required. Make it optional (with the `_guess` effect when absent.

**Comment by maykillmore** [comment]
Sir @lewismc @carueda I'd like to take up this issue if it's okay?

**Comment by veer11997** [comment]
@lewismc @carueda i want to contribute on the current project ideas and i would like to solve some of issue .

**Comment by lewismc** [comment]
@maykillmore yes please go ahead...

**Comment by lewismc** [comment]
@veer11997 thanks for registering your interest in the project. 
Arr you interested in GSoC or generally in the project? 
Are you interested in front end or backend development?

**Comment by veer11997** [comment]
@lewismc  intially i would like to go ahead with the front end development.

**Comment by carueda** [comment]
@veer11997 Thanks your interest!

As you may have already noted, https://github.com/mmisw/orr-portal is the repo for the frontend. Its [development.md](https://github.com/mmisw/orr-portal/blob/master/development.md) file should still be accurate enough, but in any case I just put together some "fresh" notes in a new wiki https://github.com/mmisw/orr-portal/wiki/Development .  Please give it a try and report back (I'd suggest  under that orr-portal repo as well, unless of course the changes under consideration also involve the backend).  Thanks again.

**Comment by lewismc** [comment]
Thanks @carueda

**Comment by lewismc** [comment]
@veer11997 are you interested in GSoC?

**Comment by veer11997** [comment]
@lewismc  i am really interested in Gsoc 2019 and want to contribute in  opensource.

**Comment by lewismc** [comment]
@veer11997 excellent. We have a couple of possible projects here. Have you see both https://github.com/ESIPFed/gsoc/issues/18 and https://github.com/ESIPFed/gsoc/issues/12 ? Do any of these interest you? If so then please consider applying to GSoC this year and begin thinking about a proposal.

**Comment by veer11997** [comment]
@lewismc  sir i am interested in the ESIPFed/gsoc#18  project .i am trying to solve the issue and as you said to go ahead to proposal i  will do it as soon as possible.thanks for your all the supports.

**Comment by veer11997** [comment]
@carueda  @lewismc  sir i had tried these and i had done it https://github.com/ mmisw/orr-portal/wiki/Development . so sir whatever  the your instruction will be given ,i will try to do.

**Comment by carueda** [comment]
@veer11997 Glad to hear the orr-portal environment setup instructions worked for you.  

Have you taken a look at the current list of orr-portal issues? We know, there are different levels of difficulty associated, and I just started marking some as `good first issue`: https://github.com/mmisw/orr-portal/labels/good%20first%20issue .  Again, let's please  continue any orr-portal related discussions under the https://github.com/mmisw/orr-portal space. Thanks.

@lewismc Do you have other suggestions re possible orr-portal issues @veer11997 could take at look? Perhaps https://github.com/mmisw/orr-portal/issues/128?

**Comment by carueda** [comment]
@veer11997 I just noted [your new account](https://mmisw.org/ont/#/user/veer11997) on the MMI ORR. That's good thanks. Perhaps you should also create one under the COR instance moving forward, http://cor.esipfed.org/ont .

**Comment by veer11997** [comment]
@carueda  yes you got that so right about my new account .at the time i am focusing on trying to solve the issue and as well as the  trying to understand about the project ESIPFed/gsoc#18 as i mentioned earlier that i would like to work on the project.

**Comment by lewismc** [comment]
@veer11997 what is the issue? Can you post an error trace?

**Comment by veer11997** [comment]
sorry !! their is my mid term held in last weak at my college so i didn't work. but i am free to work and having much more time to work at project .
