### ISSUE TITLE
returned RDF properties (for XSV input) don't look right

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-ont#72]
Using http://cor.esipfed.org/ont/~graybeal/skostest as my example:

If I download a term as RDF/XML, the term looks like
```
 <Description rdf:about="http://cor.esipfed.org/ont/~graybeal/skostest/term2">
    <rdf:type rdf:resource="http://cor.esipfed.org/ont/~graybeal/skostest/topterm"/>
    <skos:topConceptOf rdf:resource="http://cor.esipfed.org/ont/~graybeal/skostest"/>
    <skos:inScheme rdf:resource="http://cor.esipfed.org/ont/~graybeal/skostest"/>
    <ns1:hasDescription xmlns:ns1="http://cor.esipfed.org/ont/~graybeal/skostest/">Def of term two</ns1:hasDescription>
  </Description>
```

Which is what I expect. If I download the whole ontology as RDF/XML, the relevant part looks like
```
 <topterm rdf:about="http://cor.esipfed.org/ont/~graybeal/skostest/term2">
    <j.1:topConceptOf rdf:resource=""/>
    <j.1:inScheme rdf:resource=""/>
    <hasDescription>Def of term one</hasDescription>
  </topterm>
 ```
(where the j.1 is the same as skos in the earlier example).

It looks to me like the rdf:resource  values are missing in the second case.

**Comment by carueda** [comment]
Just reproduced the RDF/XML outputs as indicated.

>     <topterm rdf:about="http://cor.esipfed.org/ont/~graybeal/skostest/term2">
>        <j.1:topConceptOf rdf:resource=""/>
>        <j.1:inScheme rdf:resource=""/>
>        <hasDescription>Def of term one</hasDescription>
>      </topterm>
> It looks to me like the rdf:resource values are missing in the second case.

With `<topterm rdf:about="http://cor.esipfed.org/ont/~graybeal/skostest/term2">` indicating that term2 is an instance of topterm, I can see 4 triples encoded there.

XML is not my preferred way of looking at things, so, looking at this with TTL instead:

(skipping some prefixes for easier inspection, and focusing on `term2`)

First the term, http://cor.esipfed.org/ont/~graybeal/skostest/term2.ttl :

```ttl
<http://cor.esipfed.org/ont/~graybeal/skostest/term2> 
  skos:inScheme <http://cor.esipfed.org/ont/~graybeal/skostest> ; 
  rdf:type <http://cor.esipfed.org/ont/~graybeal/skostest/topterm> ; 
  skos:topConceptOf <http://cor.esipfed.org/ont/~graybeal/skostest> ; 
  <http://cor.esipfed.org/ont/~graybeal/skostest/hasDescription> "Def of term two" . 
```

and the ontology http://cor.esipfed.org/ont/~graybeal/skostest.ttl :

```ttt
@base          <http://cor.esipfed.org/ont/~graybeal/skostest> .
@prefix :      <http://cor.esipfed.org/ont/~graybeal/skostest/> .
@prefix j.1:   <http://www.w3.org/2004/02/skos/core#> .
@prefix j.0:   <http://mmisw.org/ont/mmi/20081020/ontologyMetadata/> .

:topterm  a     owl:Class .

<>      a                    owl:Ontology ;
        j.0:hasResourceType  <http://mmisw.org/ont/mmi/resourcetype/keyword> ;
        ...

...

:term2  a                 :topterm ;
        :hasDescription   "Def of term two" ;
        j.1:inScheme      <> ;
        j.1:topConceptOf  <> .
```

In both cases I can see the same 4 triples with term2 as subject (note that `<>` refers to the base), so nothing missing.

(An even more explicit comparison can be done with the N-Triples serialization.)

@graybeal please review this and either close if appropriate or provide more details about the RDF/XML output.
