### ISSUE TITLE
can't fully unregister ontology

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-ont#73]
Working with ontology AWWM (https://mmisw.org/ont/~mohammedajooz/AWWM# , 20181209T171335), making this ontology private did not make it disappear from the listings. I went through all 3 versions and made them private, but it still didn't disappear.

I unregistered all 3 versions. Now when I click on the link in the ontologies list, it shows a single property. 

Same thing happened with https://mmisw.org/ont/~mohammedajooz/AWM. 

See also https://github.com/mmisw/orr-ont/issues/74.

See screenshots.

![Screen Shot 2020-04-02 at 8 10 34 AM](https://user-images.githubusercontent.com/1266896/78267202-8b1f1d80-74bb-11ea-8f44-abaac6f7eeea.png)
![Screen Shot 2020-04-02 at 8 11 04 AM](https://user-images.githubusercontent.com/1266896/78267215-8fe3d180-74bb-11ea-9e63-4caec7bd2de8.png)
![Screen Shot 2020-04-02 at 8 13 14 AM](https://user-images.githubusercontent.com/1266896/78267228-93775880-74bb-11ea-8686-13b1596dbd8a.png)

**Comment by carueda** [comment]
>making this ontology private did not make it disappear from the listings. I went through all 3 versions and made them private, but it still didn't disappear.

Admins will always see all registered ontologies regardless of visibility.  What I do is open an "incognito" window to check what's visible as a casual user.

>Now when I click on the link in the ontologies list, it shows a single property.

This sounds like the ontology unregistration completed ok (that is, from the mongo db), but not completely from the triple store.  Probably some issue with agraph upon the recent https://github.com/mmisw/orr/wiki/mmi-orr-migration-to-xdomes-vm . I'll look into that.

**Comment by carueda** [comment]
I just repopulated the triple store (which you can do as admin - https://mmisw.org/ont#/ts) and the links above now respond with "IRI not found"). (*Note*: I'm not saying this an actual fix to the issue. I still have to look into it.)

**Comment by graybeal** [comment]
Yes, I did use incognito window, including refreshing cache. The ontology was still listed.

**Comment by carueda** [comment]
>...The ontology was still listed.

Is it still listed?

**Comment by graybeal** [comment]
yes, 6th one down

![Screen Shot 2020-04-03 at 10 51 46 AM](https://user-images.githubusercontent.com/1266896/78390349-3fdb3c80-7599-11ea-8d1f-21aea4bb0509.png)

**Comment by carueda** [comment]
Ok, so it's the one listed as

         https://mmisw.org/ont/~mohammedajooz/AWWM#

which, when clicked, you get

>![image](https://user-images.githubusercontent.com/556505/78396638-90a46280-75a4-11ea-895c-4b1820effce2.png)

The trailing hash `#` has been "lost" because it's not being encoded (`%23`).

So, this is a regression as we have addressed similar issue in the past (a related entry is (https://github.com/mmisw/mmiorr/issues/213).

BTW, with proper encoding, I can see that there's an ontology registered by the IRI `https://mmisw.org/ont/~mohammedajooz/AWWM#`. 

This is hard to see with a browser, but on the command line:

```
$ http -pb get 'https://mmisw.org/ont/~mohammedajooz/AWWM%23'
<?xml version="1.0"?>
...
</rdf:RDF>

<!-- Generated by the OWL API (version 3.4.2) http://owlapi.sourceforge.net -->
```

**Comment by carueda** [comment]
BTW, the place to resolve this issue in on the GUI (orr-portal), but let's keep the entry here for now.

**Comment by carueda** [comment]
Conclusion regarding the `#` encoding issue:  This is already fixed (all involving only the frontend component) and I'll be releasing and deploying a 3.9.1 version shortly (for the MMI ORR initially).

----

@graybeal Once 3.9.1 is in place, please review the original problems in this ticket and update as appropriate.

**Comment by carueda** [comment]
3.9.1 just deployed for the MMI ORR https://mmisw.org/ont .
