### ISSUE TITLE
ontology entries are just remnants

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-ont#74]
Can you please delete (in the backend) anything related to the MMI ontology https://mmisw.org/ont/~webmining/MWSontologySVU/ ?  When I click on it I get IRI not found, but it appears in the list of ontologies.

After I unregistered the ontology at https://mmisw.org/ont/~mohammedajooz/AWM, got the same result for that ontology.

**Comment by carueda** [comment]
Let's close this one and continue with #73

**Comment by carueda** [comment]
RE-opening now that the other issue (related but not quite the same) has been resolved (3.9.1).

In this case, the ontology IRI has a trailing slash, however, it's been handled without it for resolution:

> ![image](https://user-images.githubusercontent.com/556505/78415527-26f17c00-75d7-11ea-85ee-4ac2791a895b.png)

**Comment by carueda** [comment]
@graybeal 3.9.2 deployed for the MMI ORR with fix to https://github.com/mmisw/orr-portal/issues/156.

Now, you should be able to do the unregistration with the correct IRI.

![image](https://user-images.githubusercontent.com/556505/78416869-3d9cd080-75e1-11ea-9788-4553cc7a0fa2.png)

**Comment by carueda** [comment]
ORR 3.9.2 already deployed for:
• https://mmisw.org/ont
• https://xdomes.tamucc.edu/ont
• http://cor.esipfed.org/ont
