### ISSUE TITLE
does setting ontology private affect all versions?

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-ont#75]
I identified a few ontologies on MMI ORR (see https://github.com/mmisw/orr-ont/issues/73 for examples) where the current version was set to private, but one or more older versions (not all the older versions) were set to public.

Since last year I set the ontology to private, I'm having a hard time understanding how some of the intermediate versions would be set to public, and some to private, unless (a) the original user set the ontology differently in different versions, or (b) there is a bug in applying a setting to all the versions.

What is the model for this UI, is it intended to set the value for all versions, or just the current version? (In the latter case, the current version should no longer be listed in the summary page, but an older version could be.)

In the first example in the ticket referenced above, the Versions drop down was only showing 3 versions, but the version tag for the ontology in the summary page was showing a more current version than the 3 listed in the drop down.  Not sure if that's more related to that ticket, this ticket, or something else; the second case appeared to show the current version of the ontology in the drop down just fine.

**Comment by carueda** [comment]
> does setting ontology private affect all versions?

No.  The visibility attribute is per version (as is status).   Example below.

> What is the model for this UI, is it intended to set the value for all versions, or just the current version?

It is set to whatever version the user is currently looking at (which could be the latest, or any other version).

----
The special `!md` format(*) can be used to retrieve all version of a registered ontology, e.g., 
 https://mmisw.org/ont/cf/parameter?format=!md

![image](https://user-images.githubusercontent.com/556505/78381579-6cd42300-758a-11ea-8308-8e0769f67581.png)

---
(*) Hmm, maybe only "documented" in emails, tracker tickets ... but I'll see whether to add it to https://mmisw.org/orrdoc/api/#format-parameter

(@lewismc just an fyi)

**Comment by carueda** [comment]
Just added this section for the doc: https://mmisw.org/orrdoc/api/#special-format-for-metadata
