### ISSUE TITLE
weird issue accessing ontology

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-ont#76]
In another edge case, clicking on  the middle ontology in the first image (that shows a section of a search page for 'waseem') yields the page in the second image. Note that URL in the second image has 'ont#' as the ontology name.

![Screen Shot 2020-04-03 at 10 02 32 PM](https://user-images.githubusercontent.com/1266896/78419110-1a7d1b80-75f7-11ea-9a5e-42bfc52946d5.png)

![Screen Shot 2020-04-03 at 10 03 14 PM](https://user-images.githubusercontent.com/1266896/78419111-1b15b200-75f7-11ea-9825-cdeddf569d6a.png)

**Comment by graybeal** [comment]
Ewwww.  Even worse, clicking on the main logo for the repository to go to its home page takes you to https://mmisw.org/ont#/, which of course is empty. I *really* can't imagine how that happens.

**Comment by graybeal** [comment]
@carueda See slack for additional comments.

**Comment by carueda** [comment]
Seems like this user `wa_mj_ra_ka` registered an ontology whose IRI happens to coincide with the user page itself:  https://mmisw.org/ont/~wa_mj_ra_ka 

So, yes, this is an edge case.  

And yes, redirecting to https://mmisw.org/ont#/user/wa_mj_ra_ka is the expected dispatch for a user page.

For resolving the actual ontology, one can use the `iri` parameter:

https://mmisw.org/ont?iri=https://mmisw.org/ont/~wa_mj_ra_ka

----

>clicking on the main logo for the repository to go to its home page takes you to https://mmisw.org/ont#/, which of course is empty. I really can't imagine how that happens.

Why empty?  It's just the main ORR page and it works OK for me.  Maybe some cache issue in your browser?

**Comment by graybeal** [comment]
Well, it was empty for me. I can't tell you why, but I thought of ont# as a different page. It's not of course, you're right.
